apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: erik20202/moviesentiment:v4
        env:
        - name: APP_SETTINGS
          value: config.DevelopmentConfig
        ports:
        - containerPort: 5000
